
title: Blog

author:
  name: Siddhant
  email: "siddhantkumarupmanyu@gmail.com"

description: 
  non FL directed notes... 🥺

header_pages:
  - scratchpad.md
  - about.markdown

minima:
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/duckydude20" }
    - { platform: github, user_url: "https://github.com/sku0x20/" }

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
